[package]
name = "owner_of_session"
version = "1.5.1"
edition = "2018"

[dependencies]
casper-contract = "4.0.0"
casper-types = "4.0.1"

[[bin]]
name = "owner_of_call"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
